# Generated by Django 4.1.6 on 2023-02-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
