# Generated by Django 4.1 on 2023-02-13 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0002_alter_esp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
